In [ ]:
# pandas: series dataframe

In [81]:
import numpy as np
import pandas as pd

In [82]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(data.values)
print(data.index)
print(type(data.index))

print(data[0])
print(data[1:3])

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 10, 7, 'd'])
print(data)
print(type(data.index[0]))
print(type(data.index[3]))

print(data[10: 'd'])


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.RangeIndex'>
1    0.50
2    0.75
dtype: float64
1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
<class 'int'>
<class 'str'>
10    0.50
7     0.75
d     1.00
dtype: float64


In [60]:
dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50}
data_dict = pd.Series(dict)
print(data_dict)
print(data_dict['B'])
print(data_dict['B':'D'])

# списки
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

data = pd.Series(5, index=[10, 20, 30])
print(data)

# словарь ключи в метки поедут
data_dict = pd.Series(dict, index=['A', 'D'])
print(data_dict)

dict1 = {"A": 10, "B": 20, "C": 30, "D": 40, "E": 50}
data1 = pd.Series(dict1)
print(data)

dict2 = {"A": 11, "B": 21, "C": 31, "D": 41, "E": 51}
data2 = pd.Series(dict2)
print(data)

df = pd.DataFrame({1: data1, 2: data2})
print(df)
print(df.index)
print(type(df.index))
print(df.columns)
print(type(df.columns))

print(df[1])
print(df[2])

df = pd.DataFrame({1: data1})
print(df)
print(df.values)

df = pd.DataFrame(data1, columns=['rrr'])
print(df)

print(pd.DataFrame([{"a": i, "b": 2 * i} for i in range(4)]))
# Nan - Not a Number
print(pd.DataFrame(np.zeros((3, 4))))


A    10
B    20
C    30
D    40
E    50
dtype: int64
20
B    20
C    30
D    40
dtype: int64
0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
10    5
20    5
30    5
dtype: int64
A    10
D    40
dtype: int64
10    5
20    5
30    5
dtype: int64
10    5
20    5
30    5
dtype: int64
    1   2
A  10  11
B  20  21
C  30  31
D  40  41
E  50  51
Index(['A', 'B', 'C', 'D', 'E'], dtype='str')
<class 'pandas.Index'>
RangeIndex(start=1, stop=3, step=1)
<class 'pandas.RangeIndex'>
A    10
B    20
C    30
D    40
E    50
Name: 1, dtype: int64
A    11
B    21
C    31
D    41
E    51
Name: 2, dtype: int64
    1
A  10
B  20
C  30
D  40
E  50
[[10]
 [20]
 [30]
 [40]
 [50]]
   rrr
A   10
B   20
C   30
D   40
E   50
   a  b
0  0  0
1  1  2
2  2  4
3  3  6
     0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0


In [66]:
# INDEX - способ сослаться на данные в сериес или датафрейм
index = pd.Index([2,5,3,5,71])
print(index)
print(type(index))

print(index[1])
print(index[::2])

# индексы менять нельзя

Index([2, 5, 3, 5, 71], dtype='int64')
<class 'pandas.Index'>
5
Index([2, 3, 71], dtype='int64')


In [69]:
index1 = pd.Index([2,5,3,5,71])
index2 = pd.Index([1,2,51,4,99])

print(index1.intersection(index2))
print(index1.union(index2))

Index([2], dtype='int64')
Index([1, 2, 3, 4, 5, 5, 51, 71, 99], dtype='int64')


In [76]:
# NumPy
# индексация arr[1, 2]
# срезы arr[::]
# маскирование arr[arr>5]
# arr[0, [1, 5]], arr[:, [1, 5]]

data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
print(data)

print(data["a"])
print("a" in data)
print("a1" in data)

print(list(data.items()))

print(data)
data["a"] = 99

data["a1"] = 999
print(data)

print(data["c":"a1"])

print(data[2:4])
print(data[2:])

print(data[(data > 0.3) & (data < 0.8)])

print(data.loc[["c", "a"]])

print(data.iloc[[2, 0]])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
True
False
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
a      99.00
b       0.50
c       0.75
d       1.00
a1    999.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
c    0.75
d    1.00
dtype: float64
c       0.75
d       1.00
a1    999.00
dtype: float64
b    0.50
c    0.75
dtype: float64
c     0.75
a    99.00
dtype: float64
c     0.75
a    99.00
dtype: float64


In [97]:
# атрибуты-индексаторы

dict1 = {"A": 10, "B": 20, "C": 30, "D": 40, "E": 50, "S": 1}
data1 = pd.Series(dict1)
print(data)

dict2 = {"A": 11, "B": 21, "C": 31, "D": 41, "E": 51}
data2 = pd.Series(dict2)
print(data)

df = pd.DataFrame({"dict_01": data1, "dict_02": data2})
print(df)

# print(df['dict_01'])
# print(df.dict_01)

df["new"] = df["dict_01"]
print(df)

df["new1"] = df["dict_01"] / df["dict_02"]
print(df)

print(df.values)

print(df.T)

print(df["dict_01"])  # столбец
print(df.values[0])  # строка


print("pskmvc")
print(df)

print(df.loc["A":"C", :"dict_02"])
print(df.iloc[:3, :2])

df.loc[df.dict_02 > 30, ["new1", "dict_01"]] = 36
print(df)

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
   dict_01  dict_02
A       10     11.0
B       20     21.0
C       30     31.0
D       40     41.0
E       50     51.0
S        1      NaN
   dict_01  dict_02  new
A       10     11.0   10
B       20     21.0   20
C       30     31.0   30
D       40     41.0   40
E       50     51.0   50
S        1      NaN    1
   dict_01  dict_02  new      new1
A       10     11.0   10  0.909091
B       20     21.0   20  0.952381
C       30     31.0   30  0.967742
D       40     41.0   40  0.975610
E       50     51.0   50  0.980392
S        1      NaN    1       NaN
[[10.         11.         10.          0.90909091]
 [20.         21.         20.          0.95238095]
 [30.         31.         30.          0.96774194]
 [40.         41.         40.          0.97560976]
 [50.         51.         50.          0.98039216]
 [ 1.                 nan  1.                 nan]]
               

In [95]:
rng = np.random.default_rng(1)
s = pd.Series(rng.integers(0, 10, 6))

print(s)

print(np.exp(s))


0    4
1    5
2    7
3    9
4    0
5    1
dtype: int64
0      54.598150
1     148.413159
2    1096.633158
3    8103.083928
4       1.000000
5       2.718282
dtype: float64


In [100]:
df = pd.DataFrame(rng.integers(1, 10, (3, 4)), columns=["A", "B", "C", "D"])
print(df)

df = pd.DataFrame({"dict_01": data1, "dict_02": data2})
print(df)

print(data1 + data2)

print(np.add(data1, data2))

print(data1.add(data2, fill_value=1))

df1 = pd.DataFrame({"dict_01": data1, "dict_02": data2})
print(df)

df2 = pd.DataFrame({"dict_10": data1, "dict_02": data2})
print(df)

print(df1 + df2)

print(df1.add(df2, fill_value = df.values.sum()))


   A  B  C  D
0  9  3  7  2
1  3  9  4  5
2  3  2  4  6
   dict_01  dict_02
A       10     11.0
B       20     21.0
C       30     31.0
D       40     41.0
E       50     51.0
S        1      NaN
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
S      NaN
dtype: float64
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
S      NaN
dtype: float64
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
S      2.0
dtype: float64
   dict_01  dict_02
A       10     11.0
B       20     21.0
C       30     31.0
D       40     41.0
E       50     51.0
S        1      NaN
   dict_01  dict_02
A       10     11.0
B       20     21.0
C       30     31.0
D       40     41.0
E       50     51.0
S        1      NaN
   dict_01  dict_02  dict_10
A      NaN     22.0      NaN
B      NaN     42.0      NaN
C      NaN     62.0      NaN
D      NaN     82.0      NaN
E      NaN    102.0      NaN
S      NaN      NaN      NaN
   dict_01  dict_02  dict_10
A      NaN     22.0      NaN
B      NaN     42.0 

In [101]:
A = rng.integers(10, size=(3, 4))

print(A)

print(A[0])

print(A - A[0])

df = pd.DataFrame(A, columns=["A", "B", "C", "D"])
print(df)

print(df - df.iloc[0])

print(df.subtract(df["A"], axis=0))

[[4 7 3 6]
 [7 9 4 0]
 [7 5 8 4]]
[4 7 3 6]
[[ 0  0  0  0]
 [ 3  2  1 -6]
 [ 3 -2  5 -2]]
   A  B  C  D
0  4  7  3  6
1  7  9  4  0
2  7  5  8  4
   A  B  C  D
0  0  0  0  0
1  3  2  1 -6
2  3 -2  5 -2
   A  B  C  D
0  0  3 -1  2
1  0  2 -3 -7
2  0 -2  1 -3
