In [12]:
import numpy as np
import sys
import array

In [14]:
# динамическая типизация
x = 1
print(type(x))

x = 'hello'
print(type(x))

<class 'int'>
<class 'str'>


In [19]:
l = [True, '2', 3.0, 4]
print([type(i) for i in l])
print(sys.getsizeof(l))

l1 = []
print(sys.getsizeof(l1))

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
88
56


In [25]:
a1 = array.array('i', [])
print(type(a1))
print(sys.getsizeof(a1))

<class 'array.array'>
80


In [27]:
a1 = array.array('i', [1, 2])
print(type(a1))
print(sys.getsizeof(a1))

<class 'array.array'>
88


In [33]:
l = [1, 2, 3, 4, 5]
a = np.array(l)
ap = array.array('i', l)
# на больших данных нампи лучше
print(sys.getsizeof(l))
print(sys.getsizeof(ap))
print(sys.getsizeof(a))

104
100
152


In [38]:
# повышающее поведение типов
a = np.array([1.01, 2, 3, 4, 5, "a"])
print(type(a), a)

a = np.array([1.99, 2, 3, 4, 5], dtype=int) # если задаем тип, то округляется в меньшую сторону
print(type(a), a)

<class 'numpy.ndarray'> ['1.01' '2' '3' '4' '5' 'a']
<class 'numpy.ndarray'> [1 2 3 4 5]


In [40]:
# одномерные массивы
a = np.array(range(2, 5))
print(a)

[2 3 4]


In [44]:
# многомерные массивы
a = np.array([range(i, i+5) for i in [1, 2, 3]])
print(a)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [64]:
#  c нуля
print(np.zeros(10, dtype=int))
#  c единиц
print(np.ones((3, 5), dtype=float))
#  предопределенные массивы
print(np.full((3, 3), 3.1416, dtype=float))
#  линейная последовательность чисел
print(np.arange(0, 20, 2))
# генерация в интервале с одинаковыми промежутками между собой
print(np.linspace(0, 1, 11))
# равномерное распределение от 0 до 1
print(np.random.random((2, 4)))
# нормальное распределение от 0 до 1
print(np.random.normal(0, 1, (2, 4)))
# равномерное распределение в интервале (х,у)
print(np.random.randint(0, 5, (2, 2)))
# единичная матрица
print(np.eye(5, dtype = int))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]
 [3.1416 3.1416 3.1416]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[[0.39577247 0.65486328 0.6211139  0.67129044]
 [0.88338551 0.74656219 0.82199622 0.97518862]]
[[ 0.79719034  0.88386329  0.54985155 -0.60382243]
 [-0.64114013  1.15646247  1.19373096  1.15734145]]
[[1 2]
 [1 2]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [72]:
# типы данных
a1 = np.zeros(10, dtype = int) #python
a2 = np.zeros(10, dtype = 'int16') #np
a3 = np.zeros(10, dtype = np.int16)#np
print(a1, type(a1), a1.dtype) #python
print(a2, type(a2), a2.dtype)  #np
print(a3, type(a3), a3.dtype) #np

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'> int64
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'> int16
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'> int16


In [ ]:
#Numerical Python = NumPy

# - атрибуты массивов
# - индексация
# - срезы
# - изменение форм массивов
# - объединение и разбиение

In [78]:
# Атрибуты ndim - число размерностей, shape - размер каждой размерности, size - общий размер массива

np.random.seed(1)
x1 = np.random.randint(10, size = 3)
print(x1)
print(x1.ndim, x1.shape, x1.size)

x2 = np.random.randint(10, size=(3, 2))
print(x2)
print(x2.ndim, x2.shape, x2.size)

x3 = np.random.randint(10, size=(3, 2, 2))
print(x3)
print(x3.ndim, x3.shape, x3.size)

[5 8 9]
1 (3,) 3
[[5 0]
 [0 1]
 [7 6]]
2 (3, 2) 6


In [91]:
# Индексация
# одномерные
a = np.array([1,2,3,4,5])
print(a[-2])

a[1] = 20
print(a)

# многомерные
a = np.array([[1,2], [3,4]])
a[1,0] = 100
print(a.dtype)
print(a[1,1])


4
[ 1 20  3  4  5]
int64
4
int64
[[  3   3]
 [100   4]]


In [98]:
# вставки
a = np.array([1, 2, 3, 4, 5])
a[0] = 3.14
print(a.dtype)
print(a)
a.dtype = float
print(a)
print(a.dtype)

int64
[3 2 3 4 5]
[1.5e-323 9.9e-324 1.5e-323 2.0e-323 2.5e-323]
float64


In [100]:
# Срезы - подмассив массива [начало:конец:шаг]

a = np.array([1, 2, 3, 4, 5])
print(a[:3])
print(a[3:])
print(a[1:4])
print(a[::2])
print(a[1::2])

# шаг < 0
a = np.array([1, 2, 3, 4, 5])
print(a[::-1])


[1 2 3]
[4 5]
[2 3 4]
[1 3 5]
[2 4]
[5 4 3 2 1]


In [101]:
# Срезы в многомерном массиве
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(a)
print(a[:2, :3])
print(a[:, ::2])
print(a[::-1, ::-1])
print(a[:, 0])
print(a[0, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3]
 [6 7 8]]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[ 1  6 11]
[1 2 3 4 5]


In [102]:
# Срезы в Python - копии подмассивов, в NumPy - представления

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(a)

a_2x2 = a[:2, :2]
print(a_2x2)
a_2x2[0, 0] = 999
print(a)

a_2x2 = a[:2, :2].copy()
print(a_2x2)

a_2x2[0, 0] = 333
print(a_2x2)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2]
 [6 7]]
[[999   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
[[999   2]
 [  6   7]]
[[333   2]
 [  6   7]]
[[999   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [105]:
# Изменение формы массива

a = np.arange(1, 13)
print(a, a.shape, a.ndim)

a1 = a.reshape(1, 12)
print(a1, a1.shape, a1.ndim)

print(a1[0, 3])
print(a1[0, 11])

a2 = a.reshape(2, 6)
print(a2, a2.shape, a2.ndim)

a3 = a.reshape(2, 3, 2)
print(a3, a3.shape, a3.ndim)

a4 = a.reshape(1, 12, 1, 1)
print(a4, a4.shape, a4.ndim)

print(a4[0, 2, 0, 0])

a5 = a.reshape((2, 6), order="F")
print(a5, a5.shape, a5.ndim)

a = np.arange(1, 13)
print(a, a.shape, a.ndim)

print(a1[0, 3])
print(a1[0, 11])

a2 = a[:,np.newaxis]
print(a2, a2.shape, a2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1
[[ 1  2  3  4  5  6  7  8  9 10 11 12]] (1, 12) 2
4
12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6) 2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2) 3
[[[[ 1]]

  [[ 2]]

  [[ 3]]

  [[ 4]]

  [[ 5]]

  [[ 6]]

  [[ 7]]

  [[ 8]]

  [[ 9]]

  [[10]]

  [[11]]

  [[12]]]] (1, 12, 1, 1) 4
3
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]] (2, 6) 2
[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1
4
12
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (12, 1) 2
