In [2]:
import numpy as np

In [3]:
# Слияние массивов
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6, 7])

xyz = np.concatenate([x, y, z])
print(xyz)

[1 2 3 4 5 6 7]


In [4]:
# Двумерные массивы
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

xy = np.concatenate([x, y], axis=0)
print(xy)

xy = np.concatenate([x, y], axis=1)
print(xy)

xy = np.concatenate([x, y], axis=-1)
print(xy)


xy = np.vstack([x, y])
print(xy)

xy = np.hstack([x, y])
print(xy)

xy = np.dstack([x, y])
print(xy)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [5]:
# Разбиение массивов

xy = np.vstack([x, y])
print(xy)

print(np.split(xy, [1]))

print(np.vsplit(xy, [2]))

print(np.hsplit(xy, [2]))

z = np.dstack([x, y])

print(z)

print(np.dsplit(z, [1]))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3]]), array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
[array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]]), array([[[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])]


In [6]:
# Универсальные функции

x = np.arange(1, 10)
print(x)
print(x.shape)


def f(x):
    out = np.empty(len(x))
    for i in range(len(x)):
        out[i] = 1.0 / x[i]
    return out


print(f(x))
print(1.0 / x)

[1 2 3 4 5 6 7 8 9]
(9,)
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]


In [7]:
# УФ. Арифметические операции

x = np.arange(5)
print(x)
print(x + 1)  # add
print(x - 1)  # substract
print(x * 2)
print(x / 2)
print(x // 2)

print(-x)
print(x**2)  # power
print(x % 2)
print(x * 2 - 2)


print(x + 1)
print(np.add(x, 1))

x = np.arange(-5, 5)
print(x)
print(abs(x))
print(np.abs(x))
print(np.absolute(x))

x = np.array([3 + 4j, 4 - 3j])
print(abs(x))
print(np.abs(x))

[0 1 2 3 4]
[1 2 3 4 5]
[-1  0  1  2  3]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[0 0 1 1 2]
[ 0 -1 -2 -3 -4]
[ 0  1  4  9 16]
[0 1 0 1 0]
[-2  0  2  4  6]
[1 2 3 4 5]
[1 2 3 4 5]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[5 4 3 2 1 0 1 2 3 4]
[5 4 3 2 1 0 1 2 3 4]
[5 4 3 2 1 0 1 2 3 4]
[5. 5.]
[5. 5.]


In [9]:
# УФ. тригонометрические функции
# sin, cos, tan, asin, acos, atan

# УФ. показательные и логарифмы
# exp, power, log, log2, log10

x = [0.000000001, 0.0001, 0.001, 0.01, 0.1]

print("exp = ", np.exp(x))
print("exp - 1= ", np.expm1(x))

print("log = ", np.log(x))
print("log(1+x) = ", np.log1p(x))

exp =  [1.         1.00010001 1.0010005  1.01005017 1.10517092]
exp - 1=  [1.00000000e-09 1.00005000e-04 1.00050017e-03 1.00501671e-02
 1.05170918e-01]
log =  [-20.72326584  -9.21034037  -6.90775528  -4.60517019  -2.30258509]
log(1+x) =  [9.99999999e-10 9.99950003e-05 9.99500333e-04 9.95033085e-03
 9.53101798e-02]


In [10]:
# УФ.

x = np.arange(5)
print(x)
y = x * 10
print(y)

z = np.empty(len(x))
y = np.multiply(x, 10, out=z)
print(y)

x = np.arange(5)
z = np.zeros(10)
print(x)
print(z)

z[::2] = x * 10

print(z)

z = np.zeros(10)
np.multiply(x, 10, out=z[::2])

print(z)

[0 1 2 3 4]
[ 0 10 20 30 40]
[ 0. 10. 20. 30. 40.]
[0 1 2 3 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [11]:
# Сводные показатели
x = np.arange(1, 5)

print(x)
print(np.add.reduce(x))
print(np.add.accumulate(x))

print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))

print(np.sum(x))
print(np.cumsum(x))

print(np.prod(x))
print(np.cumprod(x))

x = np.arange(1, 10)
print(np.add.outer(x, x))

print(np.multiply.outer(x, x))

[1 2 3 4]
10
[ 1  3  6 10]
24
[ 1  2  6 24]
10
[ 1  3  6 10]
24
[ 1  2  6 24]
[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [12]:
# Агрегирование данных

s = np.random.random(100)
print(sum(s))
print(np.sum(s))

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.sum(a))
print(sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

print(a.sum())
print(a.sum(0))
print(a.sum(1))

print(sum(a, 1))

# Минимум / максимум

s = np.random.random(100)
print(min(s))
print(np.min(s))

print(max(s))
print(np.max(s))

52.851975489619925
52.85197548961992
55
[ 7  9 11 13 15]
[ 7  9 11 13 15]
[15 40]
55
[ 7  9 11 13 15]
[15 40]
[ 8 10 12 14 16]
0.008817542079260221
0.008817542079260221
0.9950949254189096
0.9950949254189096


In [13]:
# mean, std, var, median, argmin, argmax, percentile, any, all
# nan*

# Not a number - NaN

# транслирование (broadcasting)

a = np.array([1, 2, 3])
b = np.array([5, 5, 5])
print(a + b)
print(a + 5)

[6 7 8]
[6 7 8]
