In [1]:
import numpy as np

In [2]:
x = np.arange(12).reshape((3, 4))
print(x)

print(x[2])

print(x[2, [2, 0, 1]])

print(x[[2, 0, 1], 2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[10  8  9]
[10  2  6]


In [3]:
# срезы
print(x[1:])

print(x[1:, [2, 0, 1]])

[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 6  4  5]
 [10  8  9]]


In [6]:
# маскирование
m = np.array([1, 1, 1, 0], dtype=bool)
print(m)
print(m.shape)

r = np.array([0, 2])

print(r[:, np.newaxis].shape)
print(x[r[:, np.newaxis], m])

m = np.array([1, 1, 1, 0], dtype=bool)
r = np.array([0, 1, 2])

print(m.shape)

print(r.shape)

print(x[r[:, np.newaxis], m])

[ True  True  True False]
(4,)
(2, 1)
[[ 0  1  2]
 [ 8  9 10]]
(4,)
(3,)
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [9]:
# Сортировка

a = [3,2,4,5,1,6,3,55,9999,352,342,676]
print(sorted(a))

print(a)

a.sort()
print(a)

a = [3,2,4,5,1,6,3,55,9999,352,342,676]
x = np.array(a)
print(x)

print(np.sort(x))
print(x)
x.sort()
print(x)

print(x)
print(np.sort(x))
inx = np.argsort(x)
print(inx)

print(x[inx])

rng = np.random.default_rng(seed=1)
x = rng.integers(0, 10, size=(4, 6))
print(x)

print(np.sort(x, axis=1))
print(np.sort(x, axis=0))

[1, 2, 3, 3, 4, 5, 6, 55, 342, 352, 676, 9999]
[3, 2, 4, 5, 1, 6, 3, 55, 9999, 352, 342, 676]
[1, 2, 3, 3, 4, 5, 6, 55, 342, 352, 676, 9999]
[   3    2    4    5    1    6    3   55 9999  352  342  676]
[   1    2    3    3    4    5    6   55  342  352  676 9999]
[   3    2    4    5    1    6    3   55 9999  352  342  676]
[   1    2    3    3    4    5    6   55  342  352  676 9999]
[   1    2    3    3    4    5    6   55  342  352  676 9999]
[   1    2    3    3    4    5    6   55  342  352  676 9999]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[   1    2    3    3    4    5    6   55  342  352  676 9999]
[[4 5 7 9 0 1]
 [8 9 2 3 8 4]
 [2 8 2 4 6 5]
 [0 0 8 7 8 5]]
[[0 1 4 5 7 9]
 [2 3 4 8 8 9]
 [2 2 4 5 6 8]
 [0 0 5 7 8 8]]
[[0 0 2 3 0 1]
 [2 5 2 4 6 4]
 [4 8 7 7 8 5]
 [8 9 8 9 8 5]]


In [13]:
# Структурированный массив
# Массивы записей


name = ["Ирина", "Виталий", "Олег", "Саша"]
age = [23, 17, 52, 44]
weight = [55.0, 57.0, 78, 72]


i = 1
print(name[i], age[i], weight[i])

data = np.zeros(
    4, dtype={"names": ("name_", "age_", "weight_"), "formats": ("U10", "i4", "f8")}
)

print(data.dtype)

data["name_"] = name
data["age_"] = age
data["weight_"] = weight

print(data)

print(data["name_"])
print(data[0])
print(data[-1]["name_"])


data_rec = data.view(np.recarray)
print(data_rec)

print(data_rec.name_)
print(data_rec[0])
print(data_rec[-1].name_)

print(data["age_"] < 30)

print(data[data["age_"] < 30])

tp = np.dtype([("id", "i8"), ("mat", "f8", (3, 3))])

x = np.zeros(2, dtype=tp)
print(x)

x["mat"][0] = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(x)


data = [("Ирина", 23, 55), ("Виталий", 17, 57)]

dtype = {"names": ("name_", "age_", "weight_"), "formats": ("U10", "i4", "f8")}

data_rec = np.rec.array(data, dtype=dtype)

print(data_rec)

print(data_rec.name_)

Виталий 17 57.0
[('name_', '<U10'), ('age_', '<i4'), ('weight_', '<f8')]
[('Ирина', 23, 55.) ('Виталий', 17, 57.) ('Олег', 52, 78.)
 ('Саша', 44, 72.)]
['Ирина' 'Виталий' 'Олег' 'Саша']
('Ирина', 23, 55.0)
Саша
[('Ирина', 23, 55.) ('Виталий', 17, 57.) ('Олег', 52, 78.)
 ('Саша', 44, 72.)]
['Ирина' 'Виталий' 'Олег' 'Саша']
('Ирина', 23, 55.0)
Саша
[ True  True False False]
[('Ирина', 23, 55.) ('Виталий', 17, 57.)]
[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
 (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
[(0, [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
 (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
[('Ирина', 23, 55.) ('Виталий', 17, 57.)]
['Ирина' 'Виталий']
